const eTheme = {
  "Basic Light": {
    "--bgTopColor": "#e8e8e8",
    "--bgMidColor": "#dfdfdf",
    "--bgBottomColor": "#cecece",
    "--barColor": "#dddddd",
    "--barText": "#020202",
    "--fontColor": "#000",
    "--cardBorder": "#999",
    "--boxShadow": "#000",
  },
  "Basic Dark": {
    "--bgTopColor": "#010101",
    "--bgMidColor": "#121212",
    "--bgBottomColor": "#262626",
    "--barColor": "#272727",
    "--barText": "#f9f9f9",
    "--fontColor": "#EAEAEA",
    "--cardBorder": "#bbb",
    "--boxShadow": "#d2d2d2",
  },
  Toast: {
    "--bgTopColor": "#f6e8d8",
    "--bgMidColor": "#d09050",
    "--bgBottomColor": "#682511",
    "--barColor": "#EFD2A8",
    "--barText": "#332511",
    "--fontColor": "#000",
    "--cardBorder": "#522714",
    "--boxShadow": "#181002",
  },
  Avocado: {
    "--bgTopColor": "#f9f5b6",
    "--bgMidColor": "#bad149",
    "--bgBottomColor": "#123512",
    "--barColor": "#602c18",
    "--barText": "#bfd74b",
    "--fontColor": "#eee",
    "--cardBorder": "#bad149",
    "--boxShadow": "#082008",
  },  
  "Milky Way": {
    "--bgTopColor": "#22002f",
    "--bgMidColor": "#330044",
    "--bgBottomColor": "#440055",
    "--barColor": "#000",
    "--barText": "#fff",
    "--fontColor": "#fff",
    "--cardBorder": "#fff",
    "--boxShadow": "#fff",
  },
  Eggplant: {
    "--bgTopColor": "#303",
    "--bgMidColor": "#202",
    "--bgBottomColor": "#101",
    "--barColor": "#707",
    "--barText": "#fff",
    "--fontColor": "#fff",
    "--cardBorder": "#000",
    "--boxShadow": "#000",
  },
};

export const Theme = eTheme;
